name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]


board: [ "nice_nano_v2" ]
shield: [ "corne_left", "corne_right" ]
include:
  - board: nice_nano_v2
  shield: corne_left
  - board: nice_nano_v2
  shield: corne_right
  - board: nice_nano_v2
  shield: settings_reset

