name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: vaporizeer82/my_zmk/.github/build-user-config.yml@main
      
      
      #zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

